name: sumo-tf-deploy

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
    paths:
      - tests/*.log
      - detections/**/*.tf
      - buildspec.json
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#when running commit prior to a push you setup the cli parameters that should trigger a detection
env:
  POE_API_KEY: ${{ secrets.POE_API }}
  TF_VAR_SUMOLOGIC_ACCESS_ID : ${{ secrets.TF_VAR_SUMOLOGIC_ACCESS_ID }}
  TF_VAR_SUMOLOGIC_ACCESS_KEY : ${{ secrets.TF_VAR_SUMOLOGIC_ACCESS_KEY }}
permissions:
      contents: read    # This is required for actions/checkout

jobs:
  SumoLogicMonitorDeploy:
    # The type of runner that the job will run on
    runs-on: Ubuntu-latest
    environment: production
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      #deploy python and cache requirements
      - name: Setup Python Packages
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Terraform and Lint
        run: |
          sudo apt install terraform -y
          terraform fmt -check -recursive
          terraform init
          terraform plan
      - name: Run Synthetic AI tests
        run: |
          python ./sl-hcl-synth-test.py
      - name: Deploy Use Cases
        run: |
          terraform apply -auto-approve
